version: '3.8'

services:
  front-end:
    container_name: front-end
    build: frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - app-network

  back-end:
    container_name: back-end
    build: ./backend
    restart: always
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/images:/app/src/images
    env_file:
      - .env 
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:
      - app-network


volumes:
  postgres:

networks:
  app-network:
    driver: bridge
