services:
  front-end:
    container_name: matcha-front-end
    build: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: matcha-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  back-end:
    depends_on:
      - postgres
      - redis
    container_name: matcha-back-end
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/src/images:/app/src/images
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgis/postgis:17-3.4 # Use PostGIS-enabled PostgreSQL image
    platform: linux/amd64
    container_name: matcha-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: matcha-pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
