CREATE DATABASE MATCHA_DB;

\c MATCHA_DB;

CREATE TABLE users
(
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	refresh_token VARCHAR(255)
);
